name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # run git checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # setup go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      # run goreleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
          distribution: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}